name: Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Installing dependencies
        run: npm install

      - name: Bulding vite
        run: npm run build

      - name: Adding public content
        run: cp public/* dist/assets
      
      - name: Create build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundled-site
          path: dist
          retention-days: 1

  deployment:
    needs: build
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout infra
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.INFRA_REPOSITORY }}
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          sparse-checkout: site

      - name: Extracting infra script
        run: cp site/* . && rm -rf site
      
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: bundled-site
          path: dist

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_AUTH_JSON }}' # Replace with the name of your GitHub Actions secret

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
